@startuml Class Diagram
skinparam class {
    BackgroundColor LightGrey
    BorderColor Black
    ArrowColor Black
}

class ChatRoom {
    -repoName: String
    -favorite: Boolean
}

class GithubCache {
    -url: String
    -content: String
    -fetchTime: long
}

interface OnFetchChatRoom {
    +onFetchChatRoom(ChatRoom): void
}

interface OnFetchChatRooms {
    +onFetchChatRoom(List<ChatRoom>): void
}

interface OnSetChatRoom {
    +onSetChatRoom(): void
}

interface DatabaseHolder {
    +getDatabaseWrapper(): DatabaseWrapper
}

class DatabaseWrapper {

}
DatabaseWrapper ..|> DatabaseHolder
DatabaseWrapper --> OnFetchChatRoom
DatabaseWrapper --> OnSetChatRoom
DatabaseWrapper --> OnFetchChatRooms
DatabaseWrapper --* MainActivity

class Message {
    -message: String
    -sender: String
}

interface GithubAttachable {
    +getNumber(): int
    +getTitle(): String
    +getURL(): String
    +isClosed(): boolean
    +getGithubUser(): GithubUser
}

class GithubIssue {

}
GithubIssue ..|> GithubAttachable

class GithubPull {

}
GithubPull ..|> GithubAttachable

class GithubRepo {

}

class GithubUser {

}
GithubUser --* GithubRepo
GithubUser --* GithubPull
GithubUser --* GithubIssue

interface OnFetchAttachableList {
    +onFetchAttachableList(List<GithubAttachable>): void
}

interface OnFetchGithubIssues {
    +onFetchGithubIssues(List<GithubIssue>): void
}

interface OnFetchGithubPulls {
    +onFetchGithubPulls(List<GithubIssue>): void
}

interface OnFetchGithubRepo {
    +onFetchGithubRepo(GithubRepo): void
}

interface OnFetchGithubRepoList {
    +onFetchGithubRepoList(List<GithubRepo>): void
}

interface OnFetchGithubUser {
    +onFetchGithubUser(GithubUser): void
}

interface GithubHolder {
    +getGithubWrapper(): GithubWrapper
}

class GithubWrapper {

}
GithubWrapper ..|> GithubHolder
GithubWrapper --> OnFetchGithubUser
GithubWrapper --> OnFetchGithubRepoList
GithubWrapper --> OnFetchGithubRepo
GithubWrapper --> OnFetchGithubPulls
GithubWrapper --> OnFetchGithubIssues
GithubWrapper --> OnFetchAttachableList
GithubWrapper --> GithubCache
GithubWrapper --> DatabaseWrapper
GithubWrapper --* MainActivity


interface PreferencesHolder {
    +getPreferencesWrapper(): PreferencesWrapper
}

class PreferencesWrapper {

}
PreferencesWrapper ..|> PreferencesHolder
PreferencesWrapper --* MainActivity

class LoginActivity {

}

class MainActivity {

}
MainActivity ..|> GithubHolder
MainActivity ..|> DatabaseHolder
MainActivity ..|> PreferencesHolder
MainActivity ..|> OnFetchGithubUser
MainActivity --> ChatFragment
MainActivity --> ChatInfoFragment
MainActivity --> CreateChatFragment
MainActivity --> HomeFragment
MainActivity --> SettingsFragment
MainActivity --> GithubUser
MainActivity --> LoginActivity

class ChatFragment {

}
ChatFragment ..|> OnFetchAttachableList
ChatFragment --> GithubAttachable
ChatFragment --> ChatRoom

class ChatInfoFragment {

}
ChatInfoFragment --> ChatRoom
ChatInfoFragment --> DatabaseWrapper
ChatInfoFragment --> GithubWrapper
ChatInfoFragment ..|> OnFetchGithubRepo

class CreateChatFragment {

}
CreateChatFragment --> GithubWrapper
CreateChatFragment ..|> OnSetChatRoom
CreateChatFragment ..|> OnGithubRepoSelected

class HomeFragment {

}
HomeFragment --> DatabaseWrapper
HomeFragment ..|> OnFetchChatRooms
HomeFragment ..|> OnChatRoomSelected

class SettingsFragment {

}

interface OnChatRoomSelected {

}

interface OnGithubRepoSelected {

}

class ChatRoomViewHolder {

}
ChatRoomViewHolder --> ChatRoom
ChatRoomViewHolder --* ChatRoomAdapter

class GithubRepoViewHolder {

}
GithubRepoViewHolder --> GithubRepo
GithubRepoViewHolder --* GithubRepoAdapter

class MessageViewHolder {

}
MessageViewHolder --> Message
MessageViewHolder --* MessageAdapter
MessageViewHolder ..|> OnFetchImage
MessageViewHolder ..|> OnFetchGithubUser

class MessageAdapter {

}
MessageAdapter --* ChatFragment

class ChatRoomAdapter {

}
ChatRoomAdapter --* HomeFragment

class GithubRepoAdapter {

}
GithubRepoAdapter --* CreateChatFragment

interface OnFetchImage {

}

@enduml
