@startuml Class Diagram

skinparam class {
    BackgroundColor LightGrey
    BorderColor Black
    ArrowColor Black
}

' database
class GithubCache {
    -url: String
    -content: String
    -fetchTime: long
}

class Repository {
    -name: String
    -isFavorite: String
}

class DatabaseHelper {
    +setGithubCache(GithubCache): void
    +getGithubCache(String): GithubCache
    +getRepository(long): Repository
    +addRepository(Repository): long
    +removeRepository(Repository): void
    +findRepository(String): Repository
}

interface DatabaseHelperHolder {
    +getDatabaseHelper(): DatabaseHelper
}

' firebase
class FirebaseChatMessage {
    -message: String
    -time: long
    -sender: String
}

' github
class GithubWrapper {
    -githubToken: String
    +setGithubToken(String): void
    +getGitubToken(): String
    +fetchIssues(String,FetchIssuesListener): void
    +fetchPullRequests(String,FetchIssuesListener): void
    +fetchUser(String,FetchUserListener): void
    +fetchRepo(String,FetchRepoListener): void
    +fetchRepoList(String,FetchRepoListListener): void
}

interface GithubWrapperHolder {
    +getGithubWrapper(): GithubWrapper
}

class GithubRepo {
    -name: String
    -full_name: String
    -url: String
    -homepage: String
    +getName(): String
    +getFullName(): String
    +getURL(): String
    +getHomepage(): String
}

interface FetchRepoListener {
    +onFetchRepo(GithubRepo): void
}

interface FetchRepoListListener {
    +onFetchRepoList(List<GithubRepo>): void
}

abstract FetchGithubTask {
    +doInBackground(String...): String
}

class FetchGithubRepoTask {
    +onPostExecute(String): void
}

class FetchGithubRepoListTask {
    +onPostExecute(String): void
}

class FetchGithubLinkablesTask {
    +onPostExecute(String): void
}

class FetchGithubUserTask {
    +onPostExecute(String): void
}

interface FetchGithubAPIListener {
    +onFetchGithubAPI(String): void
}

class AsyncTask<String,String,Void> {

}


class GithubUser {
    -imageURL: String
    -login: String
    +getImageURL(): String
    +getLogin(): String
}

interface FetchUserListener {
    +onFetchUser(GithubUser): void
}

interface Linkable {
    +getNumber(): int
    +getTitle(): String
    +getURL(): String
    +isClosed(): bool
}

class Issue {

}

class PullRequest {

}

interface FetchLinkablesListener {
    +onFetchLinkables(List<Linkable>): void
}


'Helpers

class FetchImageTask {
    +doInBackground(String...): Bitmap
    +onPostExecute(Bitmap): void
}

interface FetchImageListener {
    +onFetchImage(Bitmap): void
}



'UI

class MainActivity {

}

class LoginFragment {

}

class HomeFragment {

}

class ChatFragment {

}

class ChatInfoFragment {

}

class CreateChatFragment {

}

class SettingsFragment {

}

class MessageCard {

}


MainActivity --> ChatFragment
MainActivity --> LoginFragment
MainActivity --> CreateChatFragment
MainActivity --> ChatInfoFragment
MainActivity --> HomeFragment
MainActivity --> SettingsFragment
MainActivity ..|> FetchImageListener
MainActivity ..|> GithubWrapperHolder
MainActivity ..|> DatabaseHelperHolder

FetchImageListener --* FetchImageTask

DatabaseHelper --* MainActivity
DatabaseHelper ..|> FetchGithubAPIListener

GithubWrapper --* MainActivity
GithubWrapper --> DatabaseHelper
GithubWrapper ..> FetchGithubUserTask
GithubWrapper ..> FetchGithubRepoTask
GithubWrapper ..> FetchGithubLinkablesTask
GithubWrapper ..> FetchGithubRepoListTask


GithubCache --o DatabaseHelper

Repository --o DatabaseHelper

Issue ..|> Linkable

Linkable --* LinkableList

LinkableList --* ChatFragment

PullRequest ..|> Linkable

GithubRepo --* ChatInfoFragment

GithubUser --* MainActivity

GithubUser --* FirebaseChatMessage

GithubRepoList --* CreateChatFragment

ChatFragment --> GithubWrapper
ChatFragment ..|> FetchLinkablesListener

FirebaseChatMessage --* MessageCard

LoginFragment --> GithubWrapper

ChatInfoFragment --> GithubWrapper
ChatInfoFragment ..|> FetchRepoListener


FetchGithubTask --|> AsyncTask
FetchGithubTask --> DatabaseHelper


CreateChatFragment --> GithubWrapper
CreateChatFragment --> DatabaseHelper
CreateChatFragment ..|> FetchRepoListListener

FetchGithubUserTask --|> FetchGithubTask

FetchGithubRepoTask --|> FetchGithubTask

FetchGithubLinkablesTask --|> FetchGithubTask

FetchRepoListener --* FetchGithubRepoTask

FetchUserListener --* FetchGithubUserTask

FetchRepoListListener --* FetchGithubRepoListTask

FetchLinkablesListener --* FetchGithubLinkablesTask

FetchGithubAPIListener --* FetchGithubTask

MessageCard --* ChatFragment
MessageCard --> ChatFragment
MessageCard ..|> FetchImageListener
MessageCard ..|> FetchUserListener
MessageCard ..|> FetchLinkablesListener

HomeFragment --> DatabaseHelper

FetchImageTask --|> AsyncTask

@enduml
