@startuml Class Diagram
skinparam class {
    BackgroundColor LightGrey
    BorderColor Black
    ArrowColor Black
}

class ChatRoom {

}

class GithubCache {

}

interface OnFetchChatRoom {

}

interface OnFetchChatRooms {

}

interface OnSetChatRoom {

}

interface DatabaseHolder {

}

class DatabaseWrapper {

}
DatabaseWrapper ..|> DatabaseHolder
DatabaseWrapper --> OnFetchChatRoom
DatabaseWrapper --> OnSetChatRoom
DatabaseWrapper --> OnFetchChatRooms
DatabaseWrapper --* MainActivity

class Message {

}

interface GithubAttachable {

}

class GithubIssue {

}
GithubIssue ..|> GithubAttachable

class GithubPull {

}
GithubPull ..|> GithubAttachable

class GithubRepo {

}

class GithubUser {

}
GithubUser --* GithubRepo

interface OnFetchAttachableList {

}

interface OnFetchGithubIssues {

}

interface OnFetchGithubPulls {

}

interface OnFetchGithubRepo {

}

interface OnFetchGithubRepoList {

}

interface OnFetchGithubUser {

}

interface GithubHolder {

}

class GithubWrapper {

}
GithubWrapper ..|> GithubHolder
GithubWrapper --> OnFetchGithubUser
GithubWrapper --> OnFetchGithubRepoList
GithubWrapper --> OnFetchGithubRepo
GithubWrapper --> OnFetchGithubPulls
GithubWrapper --> OnFetchGithubIssues
GithubWrapper --> OnFetchAttachableList
GithubWrapper --> GithubCache
GithubWrapper --> DatabaseWrapper
GithubWrapper --* MainActivity


interface PreferencesHolder {

}

class PreferencesWrapper {

}
PreferencesWrapper ..|> PreferencesHolder
PreferencesWrapper --* MainActivity

class LoginActivity {

}

class MainActivity {

}
MainActivity ..|> GithubHolder
MainActivity ..|> DatabaseHolder
MainActivity ..|> PreferencesHolder
MainActivity ..|> OnFetchGithubUser
MainActivity --> ChatFragment
MainActivity --> ChatInfoFragment
MainActivity --> CreateChatFragment
MainActivity --> HomeFragment
MainActivity --> SettingsFragment
MainActivity --> GithubUser
MainActivity --> LoginActivity

class ChatFragment {

}
ChatFragment ..|> OnFetchAttachableList
ChatFragment --> GithubAttachable

class ChatInfoFragment {

}

class CreateChatFragment {

}
CreateChatFragment --> GithubWrapper
CreateChatFragment ..|> OnSetChatRoom
CreateChatFragment ..|> OnGithubRepoSelected

class HomeFragment {

}
HomeFragment --> DatabaseWrapper
HomeFragment ..|> OnFetchChatRooms
HomeFragment ..|> OnChatRoomSelected

class SettingsFragment {

}

interface OnChatRoomSelected {

}

interface OnGithubRepoSelected {

}

class ChatRoomViewHolder {

}
ChatRoomViewHolder --> ChatRoom
ChatRoomViewHolder --* ChatRoomAdapter

class GithubRepoViewHolder {

}
GithubRepoViewHolder --> GithubRepo
GithubRepoViewHolder --* GithubRepoAdapter

class MessageViewHolder {

}
MessageViewHolder --> Message
MessageViewHolder --* MessageAdapter

class MessageAdapter {

}
MessageAdapter --* ChatFragment

class ChatRoomAdapter {

}
ChatRoomAdapter --* HomeFragment

class GithubRepoAdapter {

}
GithubRepoAdapter --* CreateChatFragment

@enduml
